CREATE TABLE `ct_config` (
 `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
 `creator` varchar(255) NOT NULL DEFAULT 'system' COMMENT '创建人',
 `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
 `modifier` varchar(255) NOT NULL DEFAULT 'system' COMMENT '修改人',
 `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
 `IS_DELETED` varchar(1) NOT NULL DEFAULT 'n' COMMENT '是否删除',
 `GROUP_CODE` varchar(32) NOT NULL COMMENT '组编码',
 `GROUP_NAME` varchar(64) NOT NULL COMMENT '组名称',
 `CODE` varchar(32) NOT NULL COMMENT '编码',
 `VALUE` varchar(255) NOT NULL COMMENT '值',
 PRIMARY KEY (`id`),
 KEY `IDX_GC_C` (`GROUP_CODE`,`CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `central_batch_task` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATOR` varchar(50) DEFAULT NULL,
  `GMT_CREATE` datetime DEFAULT NULL,
  `MODIFIER` varchar(50) DEFAULT NULL,
  `GMT_MODIFIED` datetime DEFAULT NULL,
  `IS_DELETED` varchar(5) DEFAULT NULL,
  `TASK_TYPE` varchar(50) DEFAULT NULL COMMENT '任务类型',
  `DATE_LABEL` varchar(50) DEFAULT NULL COMMENT '日期标识',
  `STATUS` varchar(50) DEFAULT NULL COMMENT '处理状态，INIT，PROCESS，SUCCESS，FAILURE，CANCEL',
  `EARLY_START_TIME` datetime DEFAULT NULL COMMENT '任务最早开始时间',
  `START_TIME` datetime DEFAULT NULL COMMENT '任务开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '任务完成时间',
  `RESULT_EXT` varchar(4096) DEFAULT NULL COMMENT '任务处理完成结果参数',
  `RETRY_TIME` int(11) DEFAULT NULL COMMENT '重试次数',
  `DELETE_PK` bigint(20) DEFAULT NULL,
  `PARAM_EXT` varchar(4096) DEFAULT NULL COMMENT '任务处理请求参数',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='任务处理表';