CREATE TABLE `ct_config` (
 `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
 `CREATOR` varchar(255) NOT NULL DEFAULT 'system' COMMENT '创建人',
 `GMT_CREATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
 `MODIFIER` varchar(255) NOT NULL DEFAULT 'system' COMMENT '修改人',
 `GMT_MODIFIED` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
 `IS_DELETED` varchar(1) NOT NULL DEFAULT 'n' COMMENT '是否删除',
 `GROUP_CODE` varchar(32) NOT NULL COMMENT '组编码',
 `GROUP_NAME` varchar(64) NOT NULL COMMENT '组名称',
 `CODE` varchar(32) NOT NULL COMMENT '编码',
 `VALUE` varchar(255) NOT NULL COMMENT '值',
 PRIMARY KEY (`id`),
 KEY `IDX_GC_C` (`GROUP_CODE`,`CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='配置表';

CREATE TABLE `ct_account` (
 `ID` bigint(20) NOT NULL AUTO_INCREMENT,
 `IS_DELETED` varchar(1) DEFAULT 'n',
 `U_ID` varchar(32) NOT NULL COMMENT 'UID',
 `PASSWORD` varchar(32) NOT NULL COMMENT '密码',
 `STATUS` varchar(1) NOT NULL DEFAULT '0' COMMENT '状态，0正常，1封号，2冻结',
 PRIMARY KEY (`ID`),
 UNIQUE KEY `IDX_UI` (`U_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='账号主ID表';

CREATE TABLE `ct_account_type` (
 `ID` bigint(20) NOT NULL AUTO_INCREMENT,
 `CREATOR` varchar(255) NOT NULL DEFAULT 'system' COMMENT '创建人',
 `GMT_CREATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
 `MODIFIER` varchar(255) NOT NULL DEFAULT 'system' COMMENT '修改人',
 `GMT_MODIFIED` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
 `IS_DELETED` varchar(1) DEFAULT 'n',
 `ACCOUNT` varchar(32) NOT NULL COMMENT '账号',
 `U_ID` varchar(32) NOT NULL COMMENT 'UID',
 `TYPE` varchar(32) NOT NULL COMMENT '类型',
 PRIMARY KEY (`ID`),
 UNIQUE KEY `IDX_T` (`ACCOUNT`,`TYPE`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='账号类型关联表';